### ISSUE TITLE
start API Documentation with onestop user api

### ISSUE THREAD

**Issue by heet434** [swciitg/one-stop-2021#133]
Start API Documentation for OneStop. We will be using OpenAPI with json syntax and Swagger for automation. 
Create the file structure for the docs, add the basic info file, servers file, and under the 'users' tag, add the paths and schemas for oneStopUser endpoints.
Here is an example: https://swc.iitg.ac.in/irbs/#introduction
Refer to https://swagger.io/specification/ for details on OpenAPI structure and format.

**Comment by heet434** [comment]
Note that Onestop user api, especially for verification and authentication, is used across many microservices integrated with Onestop, so it's documentation is crucial for developers working on projects within Onestop.

**Comment by laladwesh** [comment]
I'd like to work on this issue

**Comment by heet434** [comment]
> I'd like to work on this issue

alright, assigning it to you @laladwesh

**Comment by heet434** [comment]
updates @laladwesh ?

**Comment by Srayash** [comment]
hey @heet434 can i work on this?

**Comment by heet434** [comment]
> hey @heet434 can i work on this?
> 

Sure @Srayash , assigning you

**Comment by Srayash** [comment]
hey @heet434  kindly review #139.

**Comment by heet434** [comment]
Fixed in #140

**Comment by heet434** [comment]
Docs successfully deployed at https://swc.iitg.ac.in/test/onestop/api/v3/docs/ 🎉
